#!/usr/bin/env ruby

require_relative "OBJParser/OBJParser"
require_relative "HalfEdgeDataStructure/HalfEdgeMesh"

if __FILE__ == $PROGRAM_NAME

    simpleMesh = OBJParser.parse ARGV[0]
    heMesh = HalfEdgeMesh.new simpleMesh
    heMesh.print_info

end
