#!/usr/bin/env ruby

require_relative "OBJParser/OBJParser"
require_relative "HalfEdgeDataStructure/HalfEdgeMesh"

if __FILE__ == $PROGRAM_NAME

    mesh = OBJParser.parse ARGV[0]
    heMesh = HalfEdgeMesh.new( mesh )
    heMesh.build
    heMesh.orient
    heMesh.print_info

end